In [1]:
import numpy as np 
import pandas as pd 
import tensorflow as tf

seed = 2021
np.random.seed(seed)
tf.random.set_seed(seed)

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()

- 데이터 확인

In [3]:
digits.data[:3]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.,  0.,  0.,  3., 16., 15.,
        14.,  0.,  0.,  0.,  0.,  8., 13.,  8., 16.,  0.,  0.,  0.,  0.,
         1.,  6., 15., 11.,  0.,  0.,  0.,  1.,  8., 13., 15.,  1.,  0.,
         0.,  0.,  9., 16., 16.,  5.,  0.,  0.,  0.,  0.,  

- target데이터 확인

In [5]:
digits.target[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 타겟 원핫인코딩
from tensorflow.keras.utils import to_categorical
d_onehot = to_categorical(digits.target)
d_onehot[:3]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, d_onehot, test_size=0.2, random_state=seed)

X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((1437, 64), (360, 64), (1437, 10), (360, 10))

## 모델 정의 및 실행

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [31]:
from tensorflow.keras.callbacks import ModelCheckpoint
model_path = 'best_digit.h5'
checkpointer = ModelCheckpoint(
    model_path, monitor = 'val_loss', verbose=0, save_best_only=True
)

In [32]:
# early_stopping
from tensorflow.keras.callbacks import EarlyStopping

early_stopping= EarlyStopping(patience=100)

In [33]:
model3 = Sequential([
    Dense(60, input_dim=64, activation='relu'),
    Dense(30,activation='relu'),
    Dense(10,activation='softmax')
])

model3.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 60)                3900      
_________________________________________________________________
dense_15 (Dense)             (None, 30)                1830      
_________________________________________________________________
dense_16 (Dense)             (None, 10)                310       
Total params: 6,040
Trainable params: 6,040
Non-trainable params: 0
_________________________________________________________________


In [34]:
# 모델 컴파일
model3.compile(
    optimizer='adam',
    loss = 'categorical_crossentropy',
    metrics=['accuracy']
)

# 모델 학습
history3 = model3.fit(X_train, Y_train, validation_split=0.2, epochs=500, batch_size=50,verbose=0,callbacks=[checkpointer,early_stopping])

In [35]:
from tensorflow.keras.models import load_model
my_model = load_model('best_digit.h5')

In [36]:
my_model.evaluate(X_test,Y_test)

12/12 [==============================] - 0s 2ms/step - loss: 0.0808 - accuracy: 0.9861


[0.08080604672431946, 0.9861111044883728]